spring:
  application:
    name: ExclusiveService
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:exclusive-serivce-db.cd88gsw8c2w4.eu-central-1.rds.amazonaws.com}:${MYSQL_PORT:3306}/exclusive_service_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_SENDER_USERNAME}
    password: ${MAIL_SENDER_PASSWORD}
    properties:
      mail.debug: false
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  server:
    forward-headers-strategy: framework
expenses:
  api:
    baseUrl: "${EXPENSES_BASE_URL:http://exclusiveservice.bg:8081}"
