spring:
  application:
    name: ExclusiveService
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/exclusive_service?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
  mvc:
    hiddenmethod:
      filter:
        enabled: true

expenses:
  api:
    baseUrl: "http://localhost:8081"
